spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.h2.console.enabled=true

card.api.url=https://api.something.com/
app.kafka.enabled=false

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=rba-card-status-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.listener.missing-topics-fatal=false

app.kafka.card-status-topic=card-status-updates